Looker crawler is failed to load model [sc-30007]
MetaphorData/connectors pull request #1049
Opened 2024-12-12 22:20 UTC by alyiwang

### 🤔 Why?

Some Looker model may have invalid connection and raise value error

### 🤓 What?

- catch error and proceed without terminate the crawler

### 🧪 Tested?

Tested on customer environment 

### ☑️ Checks

- [x] My PR contains actual code changes, and I have updated the version number in `pyproject.toml`.

2024-12-12 22:23 UTC, mars-lan approved these changes

2024-12-12 22:29 UTC, mars-lan requested changes
Prefer to fail loudly so the error is not hidden to the users.

2024-12-16 19:37 UTC, mars-lan commented on metaphor/looker/lookml_parser.py
> +        if _is_ignored_model_file(model_path, ignored_model_files):
Might be better using a path relative to `bsae_dir` instead of the absolute path since this is likely run in a CI environment with an unknown base directory?

2024-12-16 19:58 UTC, alyiwang commented on metaphor/looker/lookml_parser.py
> +        if _is_ignored_model_file(model_path, ignored_model_files):
Good point, updadted

2024-12-16 20:32 UTC, mars-lan approved these changes

2024-12-16 20:39 UTC, merged