refactor synapse dedicated sqlpool  [sc-14405]
MetaphorData/connectors pull request #443
Opened 2022-12-16 00:54 UTC by pk1230h

### 🤔 Why?
refactor synapse dedicate sqlpool from API call to use system catalog views

### 🤓 What?
1. remove dedicated SQL API and use system catalog views
2. remove unused  API config
3. adjust readme

### 🧪 Tested?
unit test and manual test

2022-12-19 07:33 UTC, elic-eon reviewed
Otherwise, LGTM

2022-12-19 07:33 UTC, elic-eon commented on metaphor/synapse/extractor.py
> +            for database in self._client.get_databases(True):
Specify `is_dedicated` explicitly?

2022-12-19 07:33 UTC, elic-eon commented on metaphor/synapse/extractor.py
> +                tables = self._client.get_tables(database.name, True)
Also here

2022-12-21 03:55 UTC, pk1230h commented on metaphor/synapse/extractor.py
> +            for database in self._client.get_databases(True):
fixed

2022-12-21 03:55 UTC, pk1230h commented on metaphor/synapse/extractor.py
> +                tables = self._client.get_tables(database.name, True)
fixed

2022-12-21 04:15 UTC, elic-eon approved these changes

2022-12-21 04:15 UTC, elic-eon requested changes
Bump version

2022-12-21 08:20 UTC, elic-eon approved these changes

2022-12-21 08:40 UTC, merged