Add `OwnershipAssignment` to dbt `VirtualView`
MetaphorData/connectors pull request #653
Opened 2023-10-31 14:59 UTC by usefulalgorithm

### 🤔 Why?

Adds the ownership assignments to dbt model's virtual views.

Tracked by [SC20587](https://app.shortcut.com/metaphor-data/story/20587)

### 🤓 What?

See code changes.

### 🧪 Tested?

_**TODO**_

### TODO

- [ ] Test end-to-end
- [ ] Bump connector version

2023-10-31 17:06 UTC, mars-lan reviewed
Let's also add a config to control the desired behavior, i.e., assigning owners to dbt model, materialized tables, or both.

2023-11-01 08:19 UTC, usefulalgorithm commented on metaphor/dbt/util.py
> +            # If there's a comma in the string, treat it as a sequence of strings
I saw a model with owner = 'mars@metaphor.io,pardhu@metaphor.io', and that's definitely not a single user email!

2023-11-01 09:10 UTC, elic-eon submitted a review, later dismissed
LGTM!

2023-11-01 09:12 UTC, mars-lan commented on metaphor/dbt/README.md
> +    assignment_target: dbt_model # Valid choices: "dbt_model", "materialized_table", both. Default is "materialized_table"
```suggestion
    assignment_target: dbt_model # Valid choices: "dbt_model", "materialized_table", "both". Default is "materialized_table"
```

2023-11-01 09:14 UTC, usefulalgorithm commented on metaphor/dbt/README.md
> +    assignment_target: dbt_model # Valid choices: "dbt_model", "materialized_table", both. Default is "materialized_table"
ah missed it

2023-11-01 09:15 UTC, mars-lan commented on metaphor/dbt/config.py
> +MetaOwnershipAssignmentTarget = Literal["dbt_model", "materialized_table", "both"]
Is this the preferred method for Pydantic 2.x? We've been using enums before I believe?

2023-11-01 09:15 UTC, mars-lan commented on metaphor/dbt/util.py
> +            # If there's a comma in the string, treat it as a sequence of strings
I thought the YAML parser would automatically turn comma-separated strings into lists?

2023-11-01 09:18 UTC, usefulalgorithm commented on metaphor/dbt/config.py
> +MetaOwnershipAssignmentTarget = Literal["dbt_model", "materialized_table", "both"]
yes we have been using enums but I believe this is also fine. If you specify something illegal it just breaks, for example:

```yaml
meta_ownerships:
  - meta_key: owner
    ownership_type: Data Steward
    assignment_target: gg
```

the result:
```
2023-11-01 17:17:01:INFO:metaphor:Executing dbt.cloud connector with config file ../staging_config/DbtCloud.763c0e54-5d03-47e0-84b7-d42523b5835a.yml
Traceback (most recent call last):
  File "/Users/andy/Library/Caches/pypoetry/virtualenvs/metaphor-connectors-np3LZT1s-py3.9/bin/metaphor", line 6, in <module>
    sys.exit(main())
  File "/Users/andy/work/connectors/metaphor/__main__.py", line 35, in main
    package_main(args.config)
  File "/Users/andy/work/connectors/metaphor/dbt/cloud/__init__.py", line 6, in main
    cli_main(DbtCloudExtractor, config_file)
  File "/Users/andy/work/connectors/metaphor/common/cli.py", line 7, in cli_main
    extractor = extractor_cls.from_config_file(config_file)
  File "/Users/andy/work/connectors/metaphor/dbt/cloud/extractor.py", line 22, in from_config_file
    return DbtCloudExtractor(DbtCloudConfig.from_yaml_file(config_file))
  File "/Users/andy/work/connectors/metaphor/common/base_config.py", line 36, in from_yaml_file
    return TypeAdapter(cls).validate_python(variable_substitution(obj))
  File "/Users/andy/Library/Caches/pypoetry/virtualenvs/metaphor-connectors-np3LZT1s-py3.9/lib/python3.9/site-packages/pydantic/type_adapter.py", line 283, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for DbtCloudConfig
meta_ownerships.0.assignment_target
  Input should be 'dbt_model', 'materialized_table' or 'both' [type=literal_error, input_value='gg', input_type=str]
    For further information visit https://errors.pydantic.dev/2.4/v/literal_error
```

2023-11-01 09:20 UTC, usefulalgorithm commented on metaphor/dbt/util.py
> +            # If there's a comma in the string, treat it as a sequence of strings
maybe the yaml parser does that, but `value` here does not come from the yaml config - it is from the meta field in the dbt model

2023-11-01 09:33 UTC, mars-lan commented on metaphor/dbt/util.py
> +            # If there's a comma in the string, treat it as a sequence of strings
Got it. Let's update https://github.com/MetaphorData/connectors/blob/main/metaphor/dbt/README.md to include that behavior.

2023-11-01 09:34 UTC, mars-lan commented on metaphor/dbt/util.py
> +            # If there's a comma in the string, treat it as a sequence of strings
Actually no, we should change the incorrect example (`mars@metaphor.io,pardhu@metaphor.io`) into a list and update the doc.

2023-11-01 15:56 UTC, elic-eon submitted a review, later dismissed

2023-11-01 16:13 UTC, mars-lan requested changes
Let's address https://github.com/MetaphorData/connectors/pull/653#discussion_r1378576231 before merging.

2023-11-01 16:46 UTC, usefulalgorithm commented on metaphor/dbt/util.py
> +            # If there's a comma in the string, treat it as a sequence of strings
modified the incorrect example in another repo, and reverted this change.

2023-11-01 18:52 UTC, mars-lan reviewed
Almost there!

2023-11-01 18:52 UTC, mars-lan commented on metaphor/dbt/config.py
> +    assignment_target: MetaOwnershipAssignmentTarget = "materialized_table"
Default to `both` as that's most likely the expected behavior.

2023-11-01 18:52 UTC, mars-lan commented on metaphor/dbt/util.py
> +                if meta_ownership.assignment_target != "materialized_table":
While this logic works, it's less readable than 

```
if meta_ownership.assignment_target in ['both', 'dbt_model']:
```

2023-11-01 19:45 UTC, mars-lan approved these changes
Great work!

2023-11-01 19:45 UTC, merged