Support metabase collection
MetaphorData/connectors pull request #807
Opened 2024-03-21 14:24 UTC by elic-eon

### 🤔 Why?

To extract metabase collection information

### 🤓 What?

- Extract collection as hierarchy
- Fix dashboard's directories

### 🧪 Tested?

- Updated unit tests passed
- Ingested MCEs to dev and verified the collection is shown as we wanted

### ☑️ Checks

- [ ] My PR contains actual code changes, and I have updated the version number in `pyproject.toml`.

2024-03-21 15:55 UTC, usefulalgorithm requested changes
Use latest version of `metaphor-models`?

2024-03-21 16:03 UTC, alyiwang commented on metaphor/metabase/extractor.py
> +        slug = collection.get("slug")
what is slug?

2024-03-21 16:03 UTC, alyiwang commented on metaphor/metabase/extractor.py
> +            self._collections.get(dashboard_collection.get("id"))
Is it possible that the dashboard collection is not in `self._collections`?

2024-03-21 16:34 UTC, alyiwang commented on metaphor/metabase/extractor.py
> +            self._collections.get(dashboard_collection.get("id"))
I saw you mentioned `# Filter out personal collection` in code, if you implemented the filter, then is it possible for have a dashboard not found in `self._collections`?

2024-03-22 01:53 UTC, elic-eon commented on metaphor/metabase/extractor.py
> +                # Filter out personal collection
```suggestion
```

2024-03-22 01:57 UTC, elic-eon commented on metaphor/metabase/extractor.py
> +            self._collections.get(dashboard_collection.get("id"))
Removed`` the comment. We are extracting personal collection. If a dashboard is not found in `self._collections`, it will be at the root level.

2024-03-22 06:59 UTC, alyiwang approved these changes
LGTM

2024-03-22 07:07 UTC, usefulalgorithm approved these changes

2024-03-22 07:07 UTC, merged