Query log extraction for Postgres crawler
MetaphorData/connectors pull request #970
Opened 2024-08-29 10:08 UTC by elic-eon

### 🤔 Why?

PostgreSQL does not store the query history, or user action in the database but can be configured as logging to its log file. Therefore, we can parse the Postgres log for query log extraction

### 🤓 What?

- Extract query history from CloudWatch

### 🧪 Tested?

Test against an RDS instance.

### ☑️ Checks

- [ ] My PR contains actual code changes, and I have updated the version number in `pyproject.toml`.

2024-08-29 10:27 UTC, mars-lan commented on metaphor/postgresql/README.md
> +The connector support extract query log history from CloudWatch for RDS postgres. Please follow the [documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_LogAccess.Concept
```suggestion
The connector supports extracting query log history from CloudWatch for RDS PostgreSQL. Please follow [this documentation](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_LogAccess.Concepts.PostgreSQL.Query_Logging.html) to configure RDS to log SQL statements to CloudWatch.
```

2024-08-29 10:27 UTC, mars-lan commented on metaphor/postgresql/README.md
> +    profile_name: <aws_profile_name>  # If using AWS profile
I think we drop `session_token` & `profile_name`. While the SDK takes those parameters, setting them in crawlers is rather uncommon, especially for fully managed ones.

2024-08-29 10:27 UTC, mars-lan commented on metaphor/redshift/config.py
> +    ) # type: ignore
Why?

2024-08-29 10:29 UTC, elic-eon commented on metaphor/redshift/config.py
> +    ) # type: ignore
```
metaphor/redshift/config.py:28: error: Incompatible types in assignment (expression has type "RedshiftQueryLogConfig", base class "PostgreSQLRunConfig" defined the type as "PostgreSQLQueryLogConfig")  [assignment]```

mypy think it's wrong

2024-08-29 10:36 UTC, mars-lan commented on metaphor/redshift/config.py
> +    ) # type: ignore
Maybe it's time to adopt [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance)

2024-08-29 11:57 UTC, elic-eon commented on metaphor/redshift/config.py
> +    ) # type: ignore
SG

2024-08-30 04:51 UTC, usefulalgorithm commented on tests/postgresql/test_extractor.py
> +        is None
why does this not create a query log?

2024-08-30 04:51 UTC, usefulalgorithm commented on tests/postgresql/test_extractor.py
> +        is None
and this? this looks identical to the one that generates a query log above

2024-08-30 06:38 UTC, elic-eon commented on tests/postgresql/test_extractor.py
> +        is None
Added comment in test case, `foo` is in the `exclude_usernames`

2024-08-30 06:38 UTC, elic-eon commented on tests/postgresql/test_extractor.py
> +        is None
We don't want to collect queries without connection to any table

2024-08-30 06:53 UTC, usefulalgorithm approved these changes

2024-08-30 06:54 UTC, usefulalgorithm requested changes
LGTM, just gotta fix mypy

2024-08-30 11:10 UTC, usefulalgorithm approved these changes

2024-08-30 12:13 UTC, merged